<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Tiempo de Inicio: jueves, 26 de diciembre de 2024 1:47:55 a. m.</msg><msg code="0" type="0">objectid objectid;pnrr pnrr;globalid globalid;created_user created_user;created_date created_date;last_edited_user last_edited_user;last_edited_date last_edited_date;codice_ego1 codice_ego1;codice_ego2 codice_ego2;regione regione;provincia_ provincia_;comune comune;codice_ist codice_ist;frazione frazione;cap cap;indirizzo_ indirizzo_;particella particella;denominazi denominazi;via via;civico civico;barrato barrato;extra_urba extra_urba;precisione precisione;codice_civ codice_civ;longitudin longitudin;latitudine latitudine;ui_residen ui_residen;ui_sedi_pa ui_sedi_pa;ui_busines ui_busines;tot_uni_im tot_uni_im;particel_1 particel_1;via_new via_new;civico_new civico_new;pa_type pa_type;building_t building_t;flag_alleg flag_alleg;photo_fiel photo_fiel;photo_fi_1 photo_fi_1;photo_fi_2 photo_fi_2;status status;barratonew barratonew;longitud_1 longitud_1;latitudi_1 latitudi_1;codice_pro codice_pro;codice_com codice_com;codice_fra codice_fra;codice_str codice_str;codice_c_1 codice_c_1;al_res al_res;al_bus al_bus;al_olo al_olo;al_total al_total;top_business top_business;radio_station radio_station;power_station power_station;details details;strada strada;dateofexport dateofexport;version version;shape shape</msg><msg code="0" type="0">Authenticated with existing session.</msg><msg code="1" type="100">Error in script execution: ERROR 000229: No se puede abrir GPLYR_{134D3B9B-5D93-4B9F-88DD-781B7DBBE577}
Falló al ejecutar (MakeFeatureLayer).
</msg><msg code="1" type="100">Traceback (most recent call last):
  File "C:\Users\mrivera\Documents\Proyectos\CSVExportFiberCopAddresses-\ExportToCSVFiberCop.py", line 152, in script_tool
    arcpy.MakeFeatureLayer_management(poly_lyr, polygon_layer_name)
  File "C:\Users\mrivera\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10424, in MakeFeatureLayer
    raise e
  File "C:\Users\mrivera\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10421, in MakeFeatureLayer
    retval = convertArcObjectToPythonObject(gp.MakeFeatureLayer_management(*gp_fixargs((in_features, out_layer, where_clause, workspace, field_info), True)))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrivera\AppData\Local\Programs\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
arcgisscripting.ExecuteError: ERROR 000229: No se puede abrir GPLYR_{134D3B9B-5D93-4B9F-88DD-781B7DBBE577}
Falló al ejecutar (MakeFeatureLayer).

</msg><msg code="0" type="0">Secuencia de comandos errónea Export to CSV Fiber Cop...</msg><msg code="-2147467259" type="100">Falló al ejecutar (ExportToCSVFiberCop).</msg><msg code="0" type="3">Falló el jueves, 26 de diciembre de 2024 1:48:02 a. m. (Tiempo transcurrido: 6,65 segundos)</msg></messages>